### ISSUE TITLE
Failure when filtering on a column with only NA values

### ISSUE THREAD

**Issue by pkrog** [workflow4metabolomics/mtbls-dwnld#7]
Trying to remove rows from variable metadata output, where an NA value is found in a certain column that contains only NA values fails:
```
Traceback (most recent call last):
  File "/home/pierrick/dev/galaxy/lib/galaxy/jobs/runners/local.py", line 130, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/home/pierrick/dev/galaxy/lib/galaxy/jobs/__init__.py", line 1386, in finish
    'primary': self.tool.collect_primary_datasets(out_data, tool_working_directory, input_ext, input_dbkey)
  File "/home/pierrick/dev/galaxy/lib/galaxy/tools/__init__.py", line 1613, in collect_primary_datasets
    return output_collect.collect_primary_datasets( self, output, job_working_directory, input_ext, input_dbkey=input_dbkey )
  File "/home/pierrick/dev/galaxy/lib/galaxy/tools/parameters/output_collect.py", line 325, in collect_primary_datasets
    primary_data.set_meta()
  File "/home/pierrick/dev/galaxy/lib/galaxy/model/__init__.py", line 2038, in set_meta
    return self.datatype.set_meta( self, **kwd )
  File "/home/pierrick/dev/galaxy/lib/galaxy/datatypes/tabular.py", line 978, in set_meta
    data_row = next(reader)
StopIteration
```

**Comment by pierrickrogermele** [comment]
Tried with MTBLS404 study and value `database` inside field "Variable metadata columns NA filtering".

**Comment by pkrog** [comment]
Moved to workflow4metabolomics/isa2w4m#9.
